services:
  mysql_db:
    image: mysql:8.4
    container_name: test_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Test_Password_123!
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: Test_Password_123!
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: